/**
 * Core Types for Voice Agent One
 */

// Industry types supported
export type IndustryType =
  | 'healthcare'
  | 'dental'
  | 'salon'
  | 'spa'
  | 'fitness'
  | 'realestate'
  | 'restaurant'
  | 'legal'
  | 'accounting'
  | 'automotive'
  | 'veterinary'
  | 'photography'
  | 'consulting'
  | 'other';

// Business configuration generated by AI and stored in localStorage
export interface BusinessConfig {
  // Basic Info
  name: string;
  tagline: string;
  description: string;
  industry: IndustryType;

  // Contact
  phone: string;
  email: string;
  website?: string;

  // Address
  address: {
    street: string;
    city: string;
    state: string;
    zip: string;
    country: string;
  };

  // Hours
  hours: {
    weekdays: string;
    saturday: string;
    sunday: string;
  };

  // Staff
  staff: {
    name: string;
    title: string;
    bio?: string;
  };

  // Services (AI generated)
  services: Service[];

  // FAQs (AI generated)
  faqs: FAQ[];

  // Branding (AI generated)
  branding: {
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
  };

  // Voice Agent (AI generated)
  voiceAgent: {
    name: string;
    personality: string;
    systemPrompt: string;
    firstMessage: string;
  };

  // Testimonials (AI generated)
  testimonials: Testimonial[];

  // Industry-specific terms
  terms: {
    customer: string;      // patient, client, guest, member
    appointment: string;   // appointment, session, reservation, showing
    service: string;       // treatment, service, class, experience
  };

  // Custom knowledge base entries (user-added)
  knowledgeBase: KnowledgeBaseEntry[];
}

export interface KnowledgeBaseEntry {
  title: string;
  content: string;
}

export interface Service {
  id: string;
  name: string;
  description: string;
  duration: number; // minutes
  price: number;
  category: string;
}

export interface FAQ {
  question: string;
  answer: string;
}

export interface Testimonial {
  name: string;
  role: string;
  content: string;
  rating: number;
  avatar?: string;
}

// API Keys stored separately in localStorage
export interface APIKeys {
  openaiKey: string;
  elevenLabsAgentId: string;         // The created agent ID (auto-generated or manual)
  elevenLabsApiKey?: string;          // Creator's API key (for auto-creating agents)
  supabaseUrl?: string;
  supabaseAnonKey?: string;
  calcomLink?: string;
  webhookBaseUrl?: string;            // For n8n webhooks
}

// Complete app configuration
export interface AppConfig {
  isSetupComplete: boolean;
  setupCompletedAt?: string;
  business: BusinessConfig | null;
  apiKeys: APIKeys | null;
}

// Onboarding wizard state
export interface OnboardingState {
  step: number;
  industry: IndustryType | null;
  businessInfo: Partial<BusinessInfo> | null;
  apiKeys: Partial<APIKeys> | null;
  generatedConfig: Partial<BusinessConfig> | null;
  isGenerating: boolean;
  error: string | null;
}

export interface BusinessInfo {
  name: string;
  phone: string;
  email: string;
  website?: string;
  street: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  staffName: string;
  staffTitle: string;
  weekdayHours: string;
  saturdayHours: string;
  sundayHours: string;
}

// Dashboard types
export interface DashboardStats {
  totalCalls: number;
  totalCustomers: number;
  totalAppointments: number;
  bookingRate: number;
  avgCallDuration: number;
  todayCalls: number;
  todayAppointments: number;
  weeklyGrowth: number;
}

export interface CallLog {
  id: string;
  customerName: string;
  customerPhone?: string;
  duration: number; // seconds
  outcome: 'booked' | 'rescheduled' | 'cancelled' | 'inquiry' | 'no_action';
  timestamp: string;
  summary?: string;
}

export interface Appointment {
  id: string;
  customerName: string;
  customerEmail: string;
  customerPhone?: string;
  service: string;
  date: string;
  time: string;
  status: 'confirmed' | 'pending' | 'completed' | 'cancelled' | 'no_show';
  notes?: string;
}

// AI Generation request/response
export interface AIGenerationRequest {
  industry: IndustryType;
  businessName: string;
  location: string;
  staffName: string;
  staffTitle: string;
}

export interface AIGenerationResponse {
  tagline: string;
  description: string;
  services: Service[];
  faqs: FAQ[];
  branding: {
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
  };
  voiceAgent: {
    name: string;
    personality: string;
    systemPrompt: string;
    firstMessage: string;
  };
  testimonials: Testimonial[];
  terms: {
    customer: string;
    appointment: string;
    service: string;
  };
}
